### ISSUE TITLE
New Standard Data Export

### ISSUE THREAD

**Issue by tyler274** [evecm/ecm#12]
Perhaps a short tutorial on how to create one from the ones provided by fuzzworks?

**Comment by ggrog** [comment]
Yes, I know one is very much due.

A short tutorial isn't really in the cards.  The process involves several scripts, multiple operating systems on multiple VMs, and several bits of installed software.  CCP has changed the format of the database such that it can't just be imported anymore.

I really want to make ECM natively get data from Steve @ Fuzzworks.  He needed to create his own format for the blueprints data because CCP doesn't supply it in DB form anymore.  To use this data format requires a rewrite of the ECM DB conversion scripts.  This is my top priority with ECM.

I've been stalled with that due to RL (and because SQL scripts are painful), so, I think I will hand-roll a new data dump in the interim and cross my fingers that I can have the fuzzworks data import ready for the next eve release.

Thanks for opening the issue, it does help to know that there's actually people out there using ECM.

**Comment by tyler274** [comment]
There's plenty of people using it, I actually found out about the project from another corp in my alliance who use it (especially the ordering system)

**Comment by UnderMyBed** [comment]
I have had some decent luck dumping the CCP Official SDEs into a JSON and then getting ECM to import that. It takes forever though and puts a massive load on the server when the import is happening, You also need to do some work in MS SQL since the CCP dump are all in that.

**Comment by ggrog** [comment]
http://www.ggrog.com/ now has data dumps for the proteus release.  Let me know if there's issues.
